### ISSUE TITLE
Expected file list for zeo++ option with Boolean flag

### ISSUE THREAD

**Issue by pzarabadip** [ltalirz/aiida-zeopp#45]
I recently realized that when we are using `zeo++` flags like `res` where they accept Boolean flag, even if we set the flag to `False`, plugin still puts the expected output file in the list which results in crashing even though the calculations are done. 
The example on the effect of this issue happened in my `WorkChain` when I wanted to modify the `zeopp.parameters` at some point in the workchain and realized the issue. Currently, I resolved it by deleting the `key` from the dictionary but thought to report here, in case, we decide to fix it.

**Comment by ltalirz** [comment]
Thanks for pointing out this issue - just added a commit in #38 that should hopefully fix this (if not, it's tested now, so travis should fail).
