### ISSUE TITLE
Force 1 cpu resources 

### ISSUE THREAD

**Issue by danieleongari** [ltalirz/aiida-zeopp#52]
Since Zeopp does not allow for parallelization, 
force the resources setting to:
```
builder.metadata.options = {
    'resources': {
        'num_machines': 1,
        "tot_num_mpiprocs": 1,
    },
    'withmpi': False,
}
```
to avoid taking a full node if not correctly specified.
Shouldn't there be a setting in AiiDA that constrain serial codes' plugin to force this setting?

**Comment by ltalirz** [comment]
If we write our own builder, we can check this - not sure whether it is built-in by default to be able to enforce certain settings (our defaults are already fine, correct?).

Of course, it would be easy to check this in the Calculation plugin (when the calculation is submitted).
