### ISSUE TITLE
Consider upgrade monty version to >= 3.0.2

### ISSUE THREAD

**Issue by yakutovicha** [ltalirz/aiida-zeopp#55]
I can't resolve dependencies in aiidalab because of the `monty` package that is required to be:
https://github.com/ltalirz/aiida-zeopp/blob/30f8f6007ad00d4f6a5b7dd83191f1aa0d4d1b68/setup.json#L37

Would it be possible to migrate it to 3.0.2 or higher?

**Comment by ltalirz** [comment]
fixed in 66b9399c9c83fd3f33f63b4751815e57b0f9e875
