### ISSUE TITLE
Raise warning if CIF file shows signs of zeo++ incompatibility

### ISSUE THREAD

**Issue by ltalirz** [ltalirz/aiida-zeopp#62]
As (re)discovered by @mpougin, the zeo++ CIF parser is very fragile, and CIFs it does not understand can result in weird errors (even "out of memory" in her case).

If some of these issues are easy to detect, the `prepare_for_submission` function could check for signs of these and raise a warning or even an exception.

@mpougin @danieleongari @pzarabadip  
If we could collect examples of "working" and "broken" CIF files here, we could then implement those in the plugin.

**Comment by mpougin** [comment]
I just recently had problems with the following structure: ZIF-67_opt.cif (auto-created by AiiDA-DDEC plugin) gives "out of memory" error. I manually corrected it (ZIF-67_opt2.cif) that runs without problems
[ZIF-67_opt.txt](https://github.com/ltalirz/aiida-zeopp/files/5509402/ZIF-67_opt.txt)
[ZIF-67_opt2.txt](https://github.com/ltalirz/aiida-zeopp/files/5509403/ZIF-67_opt2.txt)

**Comment by ltalirz** [comment]
fixed directly in zeo++ by PR https://github.com/lsmo-epfl/zeopp-lsmo/pull/11

**Comment by ltalirz** [comment]
I'm closing this for the moment, but feel free to reopen when encountering issues - the zeo++ cif parser is homegrown and will never be perfect.

in case we keep running into issues, it would be very straightforward to add a normalize_cif calcfunction to the zeo++ plugin that calls manage_crystal under the hood and can be used on demand.
